export const TEXTS = {
  zh: {
    appTitle: '与主同行七分钟',
    start: '开始',
    startAgain: '重新开始',
    finished: '您已完成与主同行的七分钟！',
    continue: '继续',
    settings: '设置',
    language: '语言',
    chinese: '中文',
    english: 'English',
    french: 'Français',
    german: 'Deutsch',
    korean: '한국어',
    portuguese: 'Português',
    spanish: 'Español',
    tagalog: 'Tagalog',
    close: '关闭',
    day: '天',
    days: '天',
    startStreak: '开始',
  },
  en: {
    appTitle: 'Seven Minutes with the Lord',
    start: 'Start',
    startAgain: 'Start Again',
    finished: 'You have finished your 7 minutes with the Lord!',
    continue: 'Continue',
    settings: 'Settings',
    language: 'Language',
    chinese: 'Chinese',
    english: 'English',
    french: 'French',
    german: 'German',
    korean: 'Korean',
    portuguese: 'Portuguese',
    spanish: 'Spanish',
    tagalog: 'Tagalog',
    close: 'Close',
    day: 'day',
    days: 'days',
    startStreak: 'start',
  },
  es: {
    appTitle: '7 Minutos con el Señor',
    start: 'Iniciar',
    startAgain: 'Reiniciar',
    finished: '¡Has terminado tus 7 minutos con el Señor!',
    continue: 'Continuar',
    settings: 'Configuración',
    language: 'Idioma',
    chinese: 'Chino',
    english: 'Inglés',
    french: 'Francés',
    german: 'Alemán',
    korean: 'Coreano',
    portuguese: 'Portugués',
    spanish: 'Español',
    tagalog: 'Tagalo',
    close: 'Cerrar',
    day: 'día',
    days: 'días',
    startStreak: 'empezar',
  },
  fr: {
    appTitle: 'Sept Minutes avec le Seigneur',
    start: 'Commencer',
    startAgain: 'Recommencer',
    finished: 'Vous avez terminé vos 7 minutes avec le Seigneur!',
    continue: 'Continuer',
    settings: 'Paramètres',
    language: 'Langue',
    chinese: 'Chinois',
    english: 'Anglais',
    french: 'Français',
    german: 'Allemand',
    korean: 'Coréen',
    portuguese: 'Portugais',
    spanish: 'Espagnol',
    tagalog: 'Tagalog',
    close: 'Fermer',
    day: 'jour',
    days: 'jours',
    startStreak: 'commencer',
  },
  de: {
    appTitle: 'Sieben Minuten mit dem Herrn',
    start: 'Starten',
    startAgain: 'Neu starten',
    finished: 'Du hast deine 7 Minuten mit dem Herrn beendet!',
    continue: 'Weiter',
    settings: 'Einstellungen',
    language: 'Sprache',
    chinese: 'Chinesisch',
    english: 'Englisch',
    french: 'Französisch',
    german: 'Deutsch',
    korean: 'Koreanisch',
    portuguese: 'Portugiesisch',
    spanish: 'Spanisch',
    tagalog: 'Tagalog',
    close: 'Schließen',
    day: 'Tag',
    days: 'Tage',
    startStreak: 'anfangen',
  },
  ko: {
    appTitle: '주님과 함께하는 7분',
    start: '시작',
    startAgain: '다시 시작',
    finished: '주님과 함께하는 7분을 완료했습니다!',
    continue: '계속',
    settings: '설정',
    language: '언어',
    chinese: '중국어',
    english: '영어',
    french: '프랑스어',
    german: '독일어',
    korean: '한국어',
    portuguese: '포르투갈어',
    spanish: '스페인어',
    tagalog: '타갈로그어',
    close: '닫기',
    day: '일',
    days: '일',
    startStreak: '시작',
  },
  pt: {
    appTitle: 'Sete Minutos com o Senhor',
    start: 'Iniciar',
    startAgain: 'Começar Novamente',
    finished: 'Você terminou seus 7 minutos com o Senhor!',
    continue: 'Continuar',
    settings: 'Configurações',
    language: 'Idioma',
    chinese: 'Chinês',
    english: 'Inglês',
    french: 'Francês',
    german: 'Alemão',
    korean: 'Coreano',
    portuguese: 'Português',
    spanish: 'Espanhol',
    tagalog: 'Tagalo',
    close: 'Fechar',
    day: 'dia',
    days: 'dias',
    startStreak: 'começar',
  },
  tl: {
    appTitle: 'Pitong Minuto kasama ang Panginoon',
    start: 'Simulan',
    startAgain: 'Simulan Muli',
    finished: 'Natapos mo na ang inyong 7 minuto kasama ang Panginoon!',
    continue: 'Magpatuloy',
    settings: 'Mga Setting',
    language: 'Wika',
    chinese: 'Tsino',
    english: 'Ingles',
    french: 'Pranses',
    german: 'Aleman',
    korean: 'Koreano',
    portuguese: 'Portuges',
    spanish: 'Espanyol',
    tagalog: 'Tagalog',
    close: 'Isara',
    day: 'araw',
    days: 'mga araw',
    startStreak: 'simulan',
  },
};

export function getTexts(lang) {
  return TEXTS[lang] || TEXTS['en'];
} 